dist: xenial
services:
  - docker
script: 
  - docker image ls
  - docker-compose build
  - docker image ls
  - docker-compose up -d
  - docker-compose ps
  - sleep 60
  - docker-compose logs profilesvc
  - ./test.sh
after success:
  - docker image ls
  - docker image tag friendbook-profile $login/ProfileMgmtSvcImage
  - docker login -u $login -p password
  - docker image push $login ProfileMgmtSvcImage
  - docker logout
