dist: xenial
services:
  - docker
script: 
  - docker image ls
  - docker-compose build
  - docker image ls
  - docker-compose up -d
  - docker-compose ps
  - docker-compose logs profilesvc
  - ./test.sh
