dist: xenial
services:
  - docker
script: 
  - docker image ls
  - docker-compose build
  - docker image ls
  - docker-compose up -d
  - docker-compose ps
  - sleep 20
  - docker-compose logs profilesvc
  - ./test.sh
after_success:
  - docker image ls
  - docker image tag friendbook-profile $login/profilemgmtsvcimage
  - docker login -u $login -p $password
  - docker push $login/profilemgmtsvcimage
  - docker logout
